#!/usr/bin/env node
/* ZakTracking - bring two stale files up to the rest of the repo.
 *
 * 1. app/routes/webhooks.orders.cancelled.tsx
 *    Still calls renderMessage(), which notify.server.ts stopped exporting
 *    long ago. That single line is what has failed every build since
 *    30 August. Replaced with the version that uses the template system the
 *    other webhooks already use.
 *
 * 2. app/lib/webhook.server.ts
 *    An older copy that saved only the basics on an order - no item name, no
 *    city, no address, no cash-on-delivery balance. That is why messages say
 *    "your order" instead of the product, and why the tracking page has no
 *    address. Replaced with the current one.
 *
 * Each file is only touched if it really is the old one. A copy of whatever
 * is there now is left beside it as .bak before anything is written, and git
 * still has the original either way.
 */
import fs from "node:fs";
import path from "node:path";

const FILES = [
  {
    "path": "app/routes/webhooks.orders.cancelled.tsx",
    "only_if_contains": "renderMessage",
    "why": "still on the old renderMessage() way of building a message",
    "b64": "aW1wb3J0IHR5cGUgeyBBY3Rpb25GdW5jdGlvbkFyZ3MgfSBmcm9tICJyZWFjdC1yb3V0ZXIiOwppbXBvcnQgeyBhdXRoZW50aWNhdGUgfSBmcm9tICIuLi9zaG9waWZ5LnNlcnZlciI7CmltcG9ydCBkYiBmcm9tICIuLi9kYi5zZXJ2ZXIiOwppbXBvcnQgeyBmaXJzdERlbGl2ZXJ5LCBlbnN1cmVTaG9wLCB1cHNlcnRPcmRlciB9IGZyb20gIi4uL2xpYi93ZWJob29rLnNlcnZlciI7CmltcG9ydCB7IHF1ZXVlTWVzc2FnZSwgZXZlbnRFbmFibGVkIH0gZnJvbSAiLi4vbGliL25vdGlmeS5zZXJ2ZXIiOwppbXBvcnQgeyBibGFua1ZhcnMsIGl0ZW1MaW5lLCBtb25leSwgb3JkZXJUb3RhbCB9IGZyb20gIi4uL2xpYi90ZW1wbGF0ZXMuc2VydmVyIjsKCmV4cG9ydCBjb25zdCBhY3Rpb24gPSBhc3luYyAoeyByZXF1ZXN0IH06IEFjdGlvbkZ1bmN0aW9uQXJncykgPT4gewogIGNvbnN0IHsgc2hvcCwgdG9waWMsIHBheWxvYWQgfSA9IGF3YWl0IGF1dGhlbnRpY2F0ZS53ZWJob29rKHJlcXVlc3QpOwoKICBpZiAoIShhd2FpdCBmaXJzdERlbGl2ZXJ5KHJlcXVlc3QsIHRvcGljLCBzaG9wKSkpIHJldHVybiBuZXcgUmVzcG9uc2UoKTsKCiAgY29uc3Qgb3JkZXIgPSBwYXlsb2FkIGFzIGFueTsKICBjb25zdCBzID0gYXdhaXQgZW5zdXJlU2hvcChzaG9wKTsKICBjb25zdCByZWMgPSBhd2FpdCB1cHNlcnRPcmRlcihzLmlkLCBvcmRlcik7CgogIGF3YWl0IGRiLm9yZGVyUmVjb3JkLnVwZGF0ZSh7CiAgICB3aGVyZTogeyBpZDogcmVjLmlkIH0sCiAgICBkYXRhOiB7IGNhbmNlbGxlZEF0OiBuZXcgRGF0ZSgpIH0sCiAgfSk7CgogIGlmICghZXZlbnRFbmFibGVkKHMsICJjYW5jZWxsZWQiKSkgcmV0dXJuIG5ldyBSZXNwb25zZSgpOwoKICBjb25zdCB2ID0gYmxhbmtWYXJzKCk7CiAgdi5uYW1lID0gcmVjLmN1c3RvbWVyTmFtZSB8fCAidGhlcmUiOwogIHYub3JkZXIgPSByZWMub3JkZXJOdW1iZXI7CiAgdi5pdGVtID0gaXRlbUxpbmUob3JkZXIpOwogIHYuYW1vdW50ID0gbW9uZXkob3JkZXJUb3RhbChvcmRlciksIG9yZGVyLmN1cnJlbmN5KTsKCiAgYXdhaXQgcXVldWVNZXNzYWdlKHsKICAgIHNob3BJZDogcy5pZCwKICAgIG9yZGVySWQ6IHJlYy5pZCwKICAgIGV2ZW50OiAiY2FuY2VsbGVkIiwKICAgIHRvOiByZWMucGhvbmUsCiAgICB2YXJzOiB2LAogIH0pOwoKICByZXR1cm4gbmV3IFJlc3BvbnNlKCk7Cn07Cg=="
  },
  {
    "path": "app/lib/webhook.server.ts",
    "only_if_missing": "itemLine:",
    "why": "was not saving the item name, city, address or COD balance on an order",
    "b64": "aW1wb3J0IGRiIGZyb20gIi4uL2RiLnNlcnZlciI7CmltcG9ydCB7IGl0ZW1MaW5lLCBzaG9ydEFkZHJlc3MsIG9yZGVyVG90YWwsIGFtb3VudER1ZSB9IGZyb20gIi4vdGVtcGxhdGVzLnNlcnZlciI7CgovKioKICogU2hvcGlmeSByZXRyaWVzIGV2ZXJ5IHdlYmhvb2ssIGFuZCB0aGUgc2FtZSBldmVudCBjYW4gYXJyaXZlIHR3byBvciB0aHJlZQogKiB0aW1lcy4gRXZlcnkgZGVsaXZlcnkgY2FycmllcyBhIHVuaXF1ZSBpZCBpbiBhIGhlYWRlci4gV3JpdGluZyB0aGF0IGludG8gYQogKiB0YWJsZSBpcyB0aGUgY2hlYXBlc3QgaWRlbXBvdGVuY3kgdGhlcmUgaXMuCiAqCiAqIFRydWUgdGhlIGZpcnN0IHRpbWUgaXQgYXJyaXZlcywgZmFsc2Ugb24gZXZlcnkgcmVwZWF0LgogKgogKiBJTVBPUlRBTlQ6IGNhbGwgdGhpcyBBRlRFUiBhdXRoZW50aWNhdGUud2ViaG9vaygpLiBUaGUgYm9keSBpcyByZWFkIHRoZXJlLAogKiBidXQgdGhlIGhlYWRlcnMgYXJlIHN0aWxsIGF2YWlsYWJsZSBhZnRlcndhcmRzLgogKi8KZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGZpcnN0RGVsaXZlcnkoCiAgcmVxdWVzdDogUmVxdWVzdCwKICB0b3BpYzogc3RyaW5nLAogIHNob3A6IHN0cmluZywKKTogUHJvbWlzZTxib29sZWFuPiB7CiAgY29uc3QgaWQgPSByZXF1ZXN0LmhlYWRlcnMuZ2V0KCJ4LXNob3BpZnktd2ViaG9vay1pZCIpOwogIGlmICghaWQpIHJldHVybiB0cnVlOyAvLyBjYW5ub3QgZGVkdXBlLCBsZXQgaXQgdGhyb3VnaAoKICB0cnkgewogICAgYXdhaXQgZGIud2ViaG9va0V2ZW50LmNyZWF0ZSh7IGRhdGE6IHsgaWQsIHRvcGljLCBzaG9wIH0gfSk7CiAgICByZXR1cm4gdHJ1ZTsKICB9IGNhdGNoIHsKICAgIC8vIHVuaXF1ZSBjb25zdHJhaW50IC0+IHRoaXMgZGVsaXZlcnkgaGFzIGFscmVhZHkgYmVlbiBoYW5kbGVkCiAgICByZXR1cm4gZmFsc2U7CiAgfQp9CgovKiogRmV0Y2ggdGhlIHNob3AncyByb3csIGNyZWF0ZSBpdCBpZiB0aGVyZSBpcyBub25lLiAqLwpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZW5zdXJlU2hvcChkb21haW46IHN0cmluZykgewogIHJldHVybiBkYi5zaG9wLnVwc2VydCh7CiAgICB3aGVyZTogeyBkb21haW4gfSwKICAgIHVwZGF0ZToge30sCiAgICBjcmVhdGU6IHsgZG9tYWluIH0sCiAgfSk7Cn0KCi8qKgogKiBDb252ZXJ0cyBJbmRpYW4gbnVtYmVycyB0byBFLjE2NCwgd2hpY2ggdGhlIFdoYXRzQXBwIENsb3VkIEFQSSBkZW1hbmRzLgogKgogKiAgICI5ODc2NTQzMjEwIiAgICAgICAgLT4gIjkxOTg3NjU0MzIxMCIKICogICAiKzkxIDk4NzY1IDQzMjEwIiAgIC0+ICI5MTk4NzY1NDMyMTAiCiAqICAgIjA5ODc2NS00MzIxMCIgICAgICAtPiAiOTE5ODc2NTQzMjEwIgogKgogKiBJZiB0aGUgbnVtYmVyIGxvb2tzIHVudXNhYmxlLCBudWxsIC0gc28gbm8gbWVzc2FnZSBnb2VzIHRvIGEgd3Jvbmcgb25lLgogKi8KZXhwb3J0IGZ1bmN0aW9uIHRvRTE2NChyYXc/OiBzdHJpbmcgfCBudWxsLCBjYyA9ICI5MSIpOiBzdHJpbmcgfCBudWxsIHsKICBpZiAoIXJhdykgcmV0dXJuIG51bGw7CgogIGxldCBkID0gU3RyaW5nKHJhdykucmVwbGFjZSgvXEQvZywgIiIpOwogIGlmICghZCkgcmV0dXJuIG51bGw7CgogIC8vIGludGVybmF0aW9uYWwgZm9ybWF0IHdpdGggYSAiMDAiIHByZWZpeAogIGlmIChkLnN0YXJ0c1dpdGgoIjAwIikpIGQgPSBkLnNsaWNlKDIpOwoKICAvLyAxMCBkaWdpdCBsb2NhbCBudW1iZXIgLT4gYWRkIHRoZSBjb3VudHJ5IGNvZGUKICBpZiAoZC5sZW5ndGggPT09IDEwKSByZXR1cm4gY2MgKyBkOwoKICAvLyAxMSBkaWdpdHMgc3RhcnRpbmcgd2l0aCAwIC0+IHN0cmlwIHRoZSBTVEQgMAogIGlmIChkLmxlbmd0aCA9PT0gMTEgJiYgZC5zdGFydHNXaXRoKCIwIikpIHJldHVybiBjYyArIGQuc2xpY2UoMSk7CgogIC8vIGFscmVhZHkgY2FycmllcyBhIGNvdW50cnkgY29kZQogIGlmIChkLmxlbmd0aCA+PSAxMSAmJiBkLmxlbmd0aCA8PSAxNSkgcmV0dXJuIGQ7CgogIHJldHVybiBudWxsOwp9CgovKioKICogRmluZCB0aGUgb3JkZXIncyBwaG9uZSBudW1iZXIuCiAqCiAqIFRoZSBvcmRlciBoZXJlIGlzIGRlbGliZXJhdGU6IFNISVBQSU5HIEFERFJFU1MgZmlyc3QuCiAqCiAqIFRoZSBjdXN0b21lciBwcm9maWxlIG1heSBob2xkIGFuIG9sZCBudW1iZXIsIG9yIG9uZSBmcm9tIGFub3RoZXIgY291bnRyeSAtCiAqIHNheSBhIGN1c3RvbWVyIHdobyBsaXZlcyBhYnJvYWQgYnV0IGlzIHNlbmRpbmcgdGhlIHBhcmNlbCB0byBJbmRpYS4KICogVGhlIGRlbGl2ZXJ5IG1lc3NhZ2UgaGFzIHRvIHJlYWNoIHRoZSBwZXJzb24gd2hvIHdpbGwgcmVjZWl2ZSB0aGUgcGFyY2VsLAogKiBzbyB3ZSBsb29rIGF0IHRoZSBzaGlwcGluZyBhZGRyZXNzIG51bWJlciBmaXJzdC4KICovCmV4cG9ydCBmdW5jdGlvbiBwaWNrUGhvbmUob3JkZXI6IGFueSk6IHN0cmluZyB8IG51bGwgewogIHJldHVybiB0b0UxNjQoCiAgICBvcmRlcj8uc2hpcHBpbmdfYWRkcmVzcz8ucGhvbmUgfHwKICAgICAgb3JkZXI/LnBob25lIHx8CiAgICAgIG9yZGVyPy5jdXN0b21lcj8ucGhvbmUgfHwKICAgICAgb3JkZXI/LmJpbGxpbmdfYWRkcmVzcz8ucGhvbmUgfHwKICAgICAgbnVsbCwKICApOwp9CgovKiogVGhlIGN1c3RvbWVyJ3MgZmlyc3QgbmFtZSAtIGZvciAiSGkgUmFodWwiIGluIHRoZSBtZXNzYWdlLiAqLwpleHBvcnQgZnVuY3Rpb24gcGlja05hbWUob3JkZXI6IGFueSk6IHN0cmluZyB7CiAgY29uc3QgbiA9CiAgICBvcmRlcj8uc2hpcHBpbmdfYWRkcmVzcz8uZmlyc3RfbmFtZSB8fAogICAgb3JkZXI/LmN1c3RvbWVyPy5maXJzdF9uYW1lIHx8CiAgICBvcmRlcj8uYmlsbGluZ19hZGRyZXNzPy5maXJzdF9uYW1lIHx8CiAgICAiIjsKICByZXR1cm4gU3RyaW5nKG4pLnRyaW0oKTsKfQoKLyoqCiAqIFdoZXRoZXIgdGhpcyBpcyBDT0QuCiAqCiAqIFRoaXMgY2hlY2sgbWF0dGVycyBtb3N0LiBBIENPRCBvcmRlciBmaXJlcyBvcmRlcnMvcGFpZCB0b28gLSBidXQgV0VFS1MKICogTEFURVIsIHdoZW4gdGhlIGNvdXJpZXIgZGVwb3NpdHMgdGhlIGNhc2guIFdpdGhvdXQgdGhpcyBndWFyZCB0aGUKICogY3VzdG9tZXIgZ2V0cyAiUGF5bWVudCByZWNlaXZlZCIgMyB3ZWVrcyBvbiBhbmQgaXQgcmVhZHMgYXMgc3BhbS4KICoKICogTk9URTogd2UgZG8gbm90IHRyZWF0IHRoZSAibWFudWFsIiBnYXRld2F5IGFzIENPRC4gU2hvcGlmeSB3cml0ZXMgdGhhdAogKiBuYW1lIGRvd24gZXZlbiB3aGVuIHRoZSBzaG9wa2VlcGVyIG1hcmtzIGFuIG9yZGVyICJNYXJrIGFzIHBhaWQiIGhpbXNlbGYgLQogKiBhbmQgdGhhdCBpcyBub3QgQ09ELiBXZSBvbmx5IGNhdGNoIG5hbWVzIHRoYXQgcGxhaW5seSBzYXkgQ09ELgogKi8KZXhwb3J0IGZ1bmN0aW9uIGlzQ29kT3JkZXIob3JkZXI6IGFueSk6IGJvb2xlYW4gewogIGNvbnN0IG5hbWVzOiBzdHJpbmdbXSA9IG9yZGVyPy5wYXltZW50X2dhdGV3YXlfbmFtZXMgfHwgW107CiAgaWYgKAogICAgbmFtZXMuc29tZSgoZykgPT4KICAgICAgL2Nhc2hbXHNfLV0/b25bXHNfLV0/ZGVsaXZlcnl8KF58W15hLXpdKWNvZChbXmEtel18JCkvaS50ZXN0KFN0cmluZyhnKSksCiAgICApCiAgKSB7CiAgICByZXR1cm4gdHJ1ZTsKICB9CgogIC8vIFBhcnRpYWwtcGF5bWVudCBDT0QgYXBwcyB0YWcgdGhlIG9yZGVyIHRoZW1zZWx2ZXMgLSBDT0QgS2luZyB3cml0ZXMKICAvLyAiQ09ELVZlcmlmaWVkIi4gVGhhdCB0YWcgaXMgYSBwbGFpbiBzdGF0ZW1lbnQgdGhhdCBjYXNoIGlzIGR1ZS4KICBpZiAoLyhefFteYS16XSljb2QoW15hLXpdfCQpL2kudGVzdChTdHJpbmcob3JkZXI/LnRhZ3MgPz8gIiIpKSkgcmV0dXJuIHRydWU7CgogIC8vIEFuZCB0aGUgY2FzZSB0aGF0IGNhdWdodCB1cyBvdXQ6IHRob3NlIGFwcHMgY3JlYXRlIHRoZSBvcmRlciB3aXRoIE5PCiAgLy8gZ2F0ZXdheSBhdCBhbGwgYW5kIHNpbXBseSBsZWF2ZSB0aGUgYmFsYW5jZSB1bnBhaWQsIHdoaWNoIFNob3BpZnkgc2hvd3MKICAvLyBhcyAicGVuZGluZyIgb3IgInBhcnRpYWxseSBwYWlkIi4gTm8gZ2F0ZXdheSBuYW1lIHRvIG1hdGNoLCBidXQgbW9uZXkKICAvLyBzdGlsbCBoYXMgdG8gYmUgY29sbGVjdGVkIGF0IHRoZSBkb29yIC0gYW5kIHRoYXQgaXMgd2hhdCBDT0QgbWVhbnMgZm9yCiAgLy8gZXZlcnkgbWVzc2FnZSB0aGlzIGFwcCBzZW5kcy4KICAvLwogIC8vIEEgcHJlcGFpZCBvcmRlciB3YWl0aW5nIG9uIGl0cyBnYXRld2F5IGxvb2tzIHRoZSBzYW1lIGZvciBhIGZldyBzZWNvbmRzLgogIC8vIFdlIGFjY2VwdCB0aGF0OiBhc2tpbmcgc3VjaCBhIGN1c3RvbWVyIHRvIGNvbmZpcm0gaXMgaGFybWxlc3MsIHdoaWxlCiAgLy8gdHJlYXRpbmcgYSByZWFsIENPRCBvcmRlciBhcyBwcmVwYWlkIHNlbmRzICJwYXltZW50IHJlY2VpdmVkIiBmb3IgbW9uZXkKICAvLyB0aGF0IHdhcyBuZXZlciBwYWlkLgogIGNvbnN0IHN0YXR1cyA9IFN0cmluZyhvcmRlcj8uZmluYW5jaWFsX3N0YXR1cyA/PyAiIikudG9Mb3dlckNhc2UoKTsKICBjb25zdCBvdXRzdGFuZGluZyA9IE51bWJlcihvcmRlcj8udG90YWxfb3V0c3RhbmRpbmcgPz8gMCk7CiAgaWYgKAogICAgTnVtYmVyLmlzRmluaXRlKG91dHN0YW5kaW5nKSAmJgogICAgb3V0c3RhbmRpbmcgPiAwICYmCiAgICAoc3RhdHVzID09PSAicGVuZGluZyIgfHwgc3RhdHVzID09PSAicGFydGlhbGx5X3BhaWQiKQogICkgewogICAgcmV0dXJuIHRydWU7CiAgfQoKICByZXR1cm4gZmFsc2U7Cn0KCi8qKgogKiBDcmVhdGUgb3IgdXBkYXRlIHRoZSBvcmRlciByb3cgZnJvbSB0aGUgcGF5bG9hZC4KICoKICogVGhpcyBzaXRzIGluIG9uZSBwbGFjZSBiZWNhdXNlIG9yZGVycy9jcmVhdGUgYW5kIG9yZGVycy9wYWlkIGNhbiBhcnJpdmUKICogaW4gdGhlIFNBTUUgU0VDT05ELiBJZiBwYWlkIGdvdCB0aGVyZSBmaXJzdCBhbmQgdGhlIG9yZGVyIGhhZCBub3QgYmVlbgogKiB3cml0dGVuIHRvIHRoZSBkYXRhYmFzZSB5ZXQsIHRoZSBhbnN3ZXIgdG8gImlzIHRoaXMgQ09EPyIgY2FtZSBiYWNrIGFzCiAqICJubyBpZGVhIiBhbmQgdGhlIGd1YXJkIGZhaWxlZC4KICoKICogQm90aCBoYW5kbGVycyBub3cgY2FsbCB0aGlzIHNhbWUgZnVuY3Rpb24sIHNvIHdoaWNoZXZlciBnZXRzIHRoZXJlCiAqIGZpcnN0IC0gdGhlIHJvdyBnZXRzIGNyZWF0ZWQgYW5kIGlzQ29kIGdldHMgZmlsbGVkIGluIGNvcnJlY3RseS4KICovCmV4cG9ydCBhc3luYyBmdW5jdGlvbiB1cHNlcnRPcmRlcihzaG9wSWQ6IHN0cmluZywgb3JkZXI6IGFueSkgewogIGNvbnN0IGNvZCA9IGlzQ29kT3JkZXIob3JkZXIpOwogIGNvbnN0IHBob25lID0gcGlja1Bob25lKG9yZGVyKTsKICBjb25zdCBuYW1lID0gcGlja05hbWUob3JkZXIpOwogIGNvbnN0IG9yZGVyTnVtYmVyID0gb3JkZXIubmFtZSA/PyBgIyR7b3JkZXIub3JkZXJfbnVtYmVyID8/ICIifWA7CgogIGNvbnN0IGFkZHIgPSBvcmRlcj8uc2hpcHBpbmdfYWRkcmVzcyA/PyBvcmRlcj8uYmlsbGluZ19hZGRyZXNzID8/IHt9OwoKICBjb25zdCBjb21tb24gPSB7CiAgICBvcmRlck51bWJlciwKICAgIGN1c3RvbWVyTmFtZTogbmFtZSB8fCBudWxsLAogICAgcGhvbmUsCiAgICBlbWFpbDogb3JkZXIuZW1haWwgPz8gbnVsbCwKICAgIHRvdGFsUHJpY2U6IG9yZGVyVG90YWwob3JkZXIpLAogICAgLy8gV2hhdCBpcyBzdGlsbCB0byBiZSBjb2xsZWN0ZWQgYXQgdGhlIGRvb3IuIE9uIGEgcGFydGlhbC1wYXltZW50IENPRAogICAgLy8gb3JkZXIgdGhpcyBpcyBzbWFsbGVyIHRoYW4gdGhlIHRvdGFsLCBhbmQgaXQgaXMgdGhlIG9ubHkgZmlndXJlIHRoZQogICAgLy8gY3VzdG9tZXIgc2hvdWxkIGV2ZXIgYmUgYXNrZWQgZm9yLgogICAgb3V0c3RhbmRpbmc6IGFtb3VudER1ZShvcmRlciksCiAgICBjdXJyZW5jeTogb3JkZXIuY3VycmVuY3kgPz8gbnVsbCwKICAgIGZpbmFuY2lhbDogb3JkZXIuZmluYW5jaWFsX3N0YXR1cyA/PyBudWxsLAogICAgZ2F0ZXdheTogKG9yZGVyLnBheW1lbnRfZ2F0ZXdheV9uYW1lcyA/PyBbXSkuam9pbigiLCAiKSB8fCBudWxsLAogICAgaXNDb2Q6IGNvZCwKCiAgICAvLyBUaGVzZSB0aHJlZSBnZXQgZmlsbGVkIGluIHJpZ2h0IGhlcmUgYmVjYXVzZSB3aGVuIHRoZSBjb3VyaWVyIHVwZGF0ZQogICAgLy8gYXJyaXZlcyB3ZSBkbyBub3QgaGF2ZSBTaG9waWZ5J3MgcGF5bG9hZCBhdCBhbGwgLSBvbmx5IHRoZSB0cmFja2luZwogICAgLy8gbnVtYmVyLiBUaGVuICJQb3J0YWJsZSBCbGVuZGVyICsgMSBtb3JlIGl0ZW0iIHdvdWxkIGNvbWUgZnJvbSBub3doZXJlLgogICAgaXRlbUxpbmU6IGl0ZW1MaW5lKG9yZGVyKSwKICAgIGNpdHk6IGFkZHI/LmNpdHkgPz8gbnVsbCwKICAgIGFkZHJlc3M6IHNob3J0QWRkcmVzcyhvcmRlciksCiAgfTsKCiAgcmV0dXJuIGRiLm9yZGVyUmVjb3JkLnVwc2VydCh7CiAgICB3aGVyZTogeyBzaG9wSWRfc2hvcGlmeUlkOiB7IHNob3BJZCwgc2hvcGlmeUlkOiBTdHJpbmcob3JkZXIuaWQpIH0gfSwKICAgIHVwZGF0ZTogY29tbW9uLAogICAgY3JlYXRlOiB7IHNob3BJZCwgc2hvcGlmeUlkOiBTdHJpbmcob3JkZXIuaWQpLCAuLi5jb21tb24gfSwKICB9KTsKfQo="
  }
];

const writes = [];
let already = 0;

for (const f of FILES) {
  const p = path.resolve(f.path);
  if (!fs.existsSync(p)) {
    console.error("MISSING  " + f.path + " - is this the zaktracking repo root?");
    process.exit(1);
  }
  const text = fs.readFileSync(p, "utf8");

  if (f.only_if_contains && !text.includes(f.only_if_contains)) { already++; continue; }
  if (f.only_if_missing && text.includes(f.only_if_missing)) { already++; continue; }

  writes.push({ p, f, old: text });
}

/* whatever else is still on the old way - worth knowing before the next build */
const strays = [];
for (const dir of ["app/routes", "app/lib"]) {
  const d = path.resolve(dir);
  if (!fs.existsSync(d)) continue;
  for (const name of fs.readdirSync(d)) {
    const fp = path.join(d, name);
    if (!fs.statSync(fp).isFile()) continue;
    if (!/\.(ts|tsx)$/.test(name)) continue;
    if (writes.some((w) => w.p === fp)) continue;
    if (fs.readFileSync(fp, "utf8").includes("renderMessage")) strays.push(dir + "/" + name);
  }
}

if (!writes.length) {
  console.log("Already applied - both files are current. Nothing to do.");
} else {
  for (const w of writes) {
    fs.writeFileSync(w.p + ".bak", w.old);
    fs.writeFileSync(w.p, Buffer.from(w.f.b64, "base64"));
    console.log("written  " + w.f.path);
    console.log("         " + w.f.why);
    console.log("         old copy kept at " + w.f.path + ".bak");
  }
}

if (strays.length) {
  console.log("");
  console.log("STILL ON THE OLD WAY - these also mention renderMessage:");
  for (const s of strays) console.log("  " + s);
  console.log("Send me those and I will bring them across too.");
}

console.log("");
console.log("Now check it builds:");
console.log("  npm run build");
